# Generated by Django 5.0.6 on 2024-07-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_remove_classforget_aftercategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classforget',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
