# Generated by Django 5.0.6 on 2024-07-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_classforget_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='classforget',
            name='afterCategory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classforget',
            name='beforeCategory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classforget',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterModelTable(
            name='classforget',
            table='class_forget',
        ),
    ]
