# Generated by Django 5.0.6 on 2024-07-08 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_classforget_aftercategory_classforget_beforecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classforget',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
