# Generated by Django 5.0.6 on 2024-07-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_alter_classforget_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classforget',
            name='slug',
        ),
    ]
