# Generated by Django 5.0.6 on 2024-07-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_data', models.CharField(max_length=100)),
                ('replace_word_1', models.FloatField()),
                ('replace_word_2', models.FloatField()),
                ('replace_word_3', models.FloatField()),
                ('replace_word_4', models.FloatField()),
            ],
            options={
                'db_table': 'advice_text_word',
            },
        ),
    ]
