# Generated by Django 5.0.6 on 2024-07-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoisonProtect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=254)),
                ('progress', models.CharField(max_length=254)),
                ('pre_acc', models.CharField(max_length=254)),
                ('final_acc', models.CharField(max_length=254)),
                ('spend_time', models.CharField(max_length=254)),
                ('state', models.CharField(max_length=254)),
                ('detail', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'poison_protect',
            },
        ),
    ]
