# Generated by Django 5.0.6 on 2024-07-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_record_delete_advicetext'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table='company_record',
        ),
    ]
