# Generated by Django 4.2.14 on 2024-07-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_record_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='test',
            field=models.CharField(default='abc', max_length=254),
        ),
    ]
